### ISSUE TITLE
Fails to build with Cython 0.23

### ISSUE THREAD

**Issue by jcowgill** [Sonkun/python-sfml#119]
After installing Cython 0.23 and removing `.../hacks.cpp` from setup.py (#118), I get this error when building python-sfml:

```
cythoning src/sfml/window.pyx to src/sfml/window.cpp
building 'sfml.window' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -Iinclude -Iinclude/Includes -I/usr/include/python2.7 -c src/sfml/window.cpp -o build/temp.linux-x86_64-2.7/src/sfml/window.o -fpermissive
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
src/sfml/window.cpp:1069:89: error: ‘Style’ is not an enumerator-name
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__sf_3a__3a_Style_3a__3a_Style(enum sf::Style::Style value);
                                                                                         ^
src/sfml/window.cpp:1069:100: error: ‘Style’ in namespace ‘sf::Style’ does not name a type
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_enum__sf_3a__3a_Style_3a__3a_Style(enum sf::Style::Style value);
                                                                                                    ^
[lots more errors follow]
```

This may have something to do with this Cython changelog entry:
> Fixed type errors in conversion enum types to/from Python. Note that this imposes stricter
> correctness requirements on enum declarations.

**Comment by Sonkun** [comment]
Fixed now, sorry it took so long :s
